Description: CloudFront Static Site
Parameters:
  CFOrigin:
    Type: String
  CFAlias:
    Type: String
Mappings:
  RegionMap:
    us-east-1:
      hostedzoneID: Z2FDTNDATAQYW2
      websiteendpoint: cloudfront.amazonaws.com
Resources:
  cloudfrontdistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          DomainName: !Ref CFOrigin
        Aliases: !Ref CFAlias
        PriceClass: PriceClass_100
        DefaultCacheBehavior: 
          ViewerProtocolPolicy: allow-all
          AllowedMethods: ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
          Compress: false
          DefaultTTL: 
          ForwardedValues: 
            Cookies: 
              Forward: all
            Headers: ["*"]
        IPV6Enabled: false
Outputs:
  CFOrigins:
    Value: !Ref CFOrigin
    Description: CloudFront Origin
  CFDomainName:
    Value: !GetAtt [cloudfrontdistribution, DomainName]
    Description: URL for website hosted on S3
  CFHostedZoneID:
    Value: !FindInMap [ RegionMap, "us-east-1", hostedzoneID]
    Description: Name of S3 bucket to hold website content
  CFwebsiteendpoint:
    Value: !FindInMap [ RegionMap, "us-east-1", websiteendpoint]
    Description: Name of S3 bucket to hold website content
