Description: CloudFront para un sitio estatico
Parameters:
  CFOrigin:
    Type: String
  CFAlias:
    Type: String
Mappings:
  RegionMap:
    us-east-1:
      hostedzoneID: Z2FDTNDATAQYW2
      websiteendpoint: cloudfront.amazonaws.com
Resources:
  cloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref CFOrigin
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: ''
        Enabled: 'true'
        Comment: Some comment
        DefaultRootObject: index.html
        Aliases: 
        - !Ref CFAlias
        - !Sub
          - www.${Domain}
          - Domain: !Ref CFAlias
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
Outputs:
  CFOrigins:
    Value: !Ref CFOrigin
    Description: CloudFront Origin
  CFDomainName:
    Value: !GetAtt [cloudfrontdistribution, DomainName]
    Description: CloudFront Distribution Domain Name
  CFHostedZoneID:
    Value: !FindInMap [ RegionMap, "us-east-1", hostedzoneID]
    Description: CloudFront Hosted ZoneID
  CFwebsiteendpoint:
    Value: !FindInMap [ RegionMap, "us-east-1", websiteendpoint]
    Description: CloudFront WebSite Endpoint
