Parameters:
  Dominio:
    Type: String
  SubDominio:
    Type: String
  HostedZoneId:
    Type: String
Resources:
  myStackS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/infraestructura.dev/cloudformation/infraestructura/roberto/s3-static.yml
      Parameters:
        NameBucket: !Join 
        - '.'
        - - !Ref SubDominio
          - !Ref Dominio
  myStackCF:
    Type: AWS::CloudFormation::Stack
    DependsOn: myStackS3
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/infraestructura.dev/cloudformation/infraestructura/roberto/cloudfront.yml
      Parameters:
        CFOrigin: !GetAtt myStackS3.Outputs.DomainName
        CFAlias: !Join 
        - '.'
        - - !Ref SubDominio
          - !Ref Dominio
  myStackRoute53:
    Type: AWS::CloudFormation::Stack
    DependsOn: myStackCF
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/infraestructura.dev/cloudformation/infraestructura/roberto/route53-domain.yml
      Parameters:
        R53DomainName: !Ref Dominio
        R53SubDomainName: !Ref SubDominio
        R53HostedZoneId: !Ref HostedZoneId
        ExtHostedZoneId: !GetAtt myStackCF.Outputs.hostedzoneID
        ExtDNSName: !GetAtt myStackCF.Outputs.DomainName
Outputs:
  StackRefS3:
    Value: !Ref myStackS3
  StackRefR533:
      Value: !Ref myStackRoute53
  OutputFromNestedStack:
    Value: !GetAtt myStackS3.Outputs.S3BucketName