Description: Registrar un dominio y www
Parameters:
  R53DomainName:
    Description: Domain name for your website (example.com)
    Type: String
    Default: orbis.pe
  R53SubDomainName:
    Description: Sub Domain name for your website (example.com)
    Type: String
    Default: rc
  R53HostedZoneId:
    Description: Domain name for your website (example.com)
    Type: String
    Defautl: Z11RQHUD4WPH24
  ExtHostedZoneId:
    Description: Domain name for your website (example.com)
    Type: String
    Default: Z2FDTNDATAQYW2
  ExtDNSName:
    Description: Domain name for your website (example.com)
    Type: String
Resources:
  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref R53HostedZoneId
      Comment: Zone apex alias.
      RecordSets:
      - Name: !Join 
        - '.'
        - - !Ref R53SubDomainName
          - !Ref R53DomainName
        Type: A
        AliasTarget:
          HostedZoneId: !Ref ExtHostedZoneId
          DNSName: !Ref ExtDNSName
      - Name: !Sub
            - www.${Domain}
            - Domain: !Join 
              - '.'
              - - !Ref R53SubDomainName
                - !Ref R53DomainName
        Type: A
        AliasTarget:
          HostedZoneId: !Ref ExtHostedZoneId
          DNSName: !Ref ExtDNSName